// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTyIlcVtcq6kepZDlCtuYxyDrb12ygc8',
    appId: '1:745391285785:web:9575644a77026446dc6c88',
    messagingSenderId: '745391285785',
    projectId: 'chat-app-2d6a3',
    authDomain: 'chat-app-2d6a3.firebaseapp.com',
    storageBucket: 'chat-app-2d6a3.firebasestorage.app',
    measurementId: 'G-9Z315L6RYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPecFIGrPkDpjdfN7jrUFIc90GjaF4uFw',
    appId: '1:745391285785:android:364b04381f72f477dc6c88',
    messagingSenderId: '745391285785',
    projectId: 'chat-app-2d6a3',
    storageBucket: 'chat-app-2d6a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPukPDktGhlBijtErKJjr41Q6bRTc4Vws',
    appId: '1:745391285785:ios:3c68f35a436ee414dc6c88',
    messagingSenderId: '745391285785',
    projectId: 'chat-app-2d6a3',
    storageBucket: 'chat-app-2d6a3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPukPDktGhlBijtErKJjr41Q6bRTc4Vws',
    appId: '1:745391285785:ios:3c68f35a436ee414dc6c88',
    messagingSenderId: '745391285785',
    projectId: 'chat-app-2d6a3',
    storageBucket: 'chat-app-2d6a3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTyIlcVtcq6kepZDlCtuYxyDrb12ygc8',
    appId: '1:745391285785:web:055975b21a043f7ddc6c88',
    messagingSenderId: '745391285785',
    projectId: 'chat-app-2d6a3',
    authDomain: 'chat-app-2d6a3.firebaseapp.com',
    storageBucket: 'chat-app-2d6a3.firebasestorage.app',
    measurementId: 'G-G0R8GSNFQH',
  );
}
